[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sb_randomness = "D35p6zWDC7j1sd9Xx8NknshwHe6nzB6CHNzL87zPw4A3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/jim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
